import Wrapper from '@/components/common/wrapper';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Oversoft',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <Wrapper>{children}</Wrapper>;
}
