export const PUBLIC_API_URL = process.env.NEXT_PUBLIC_API_URI;
export const PUBLIC_API_TOKEN = process.env.NEXT_PUBLIC_API_TOKEN;

export const MINUTE_IN_MILISECONDS = 60000;
export const THREE_MINUTES_IN_MILISECONDS = MINUTE_IN_MILISECONDS * 3;
export const TEN_MINUTES_IN_MILISECONDS = MINUTE_IN_MILISECONDS * 10;
export const THIRTY_MINUTES_IN_MILISECONDS = MINUTE_IN_MILISECONDS * 30;
export const HOUR_IN_MILISECONDS = MINUTE_IN_MILISECONDS * 60;
export const DAY_IN_MILISECONDS = HOUR_IN_MILISECONDS * 24;

// Max attachment file size allowed: 25MB
export const MAX_ATTACHMENT_FILE_SIZE = 1024 * 1024 * 25;
